# Build settings
title: My blog
description: My very nice blog
author: "Maicol Nicolini"

theme: minima

#base_url: /gh-pages-minima-starter

# Minima social links
twitter_username: Nick_O_Leeney
github_username: NickOLeeney
linkedin_username: Maicol Nicolini
#rss: rss

# Minima: show excerpts in the frontpage
show_excerpts: true

minima:
  date_format: "%Y-%m-%d"

# Minima: custom header links
header_pages:
  - _pages/frontpage.md
  - _pages/about.md
  - _pages/archive.md

include:
    - _pages

exclude: 
    - .gitignore
    - docker-compose.yml
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
