# Build settings
theme: minima
title: Maicol Nicolini's Data Science Portfolio
description: In this page I'm going to show some of my Data Science studies
author: "Maicol Nicolini"
twitter_username: Nick_O_Leeney
github_username: NickOLeeney
linkedin_username: maicol-nicolini
header_pages:
  - _pages/about.md


