# Build settings
theme: minima
title: My Data Science Portfolio
description: My Personal Data Science Portfolio
author: "Maicol Nicolini"
twitter_username: Nick_O_Leeney
github_username: NickOLeeney
linkedin_username: maicol-nicolini

